# Generated by Django 4.0.2 on 2022-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(default=12312, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
