# Generated by Django 4.0.2 on 2022-07-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_car_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='registration_number',
            new_name='registration',
        ),
    ]
