# Generated by Django 4.0.2 on 2022-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_rename_registration_number_car_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
