# Generated by Django 4.0.6 on 2022-07-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_car_registration_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['license_number'], 'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
    ]
