# Generated by Django 4.0.6 on 2022-07-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_driver_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['manufacturer']},
        ),
    ]
